// <auto-generated />
using System;
using LogisticERP.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogisticERP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250822231650_migracaoinicial")]
    partial class migracaoinicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LogisticERP.Domain.Motorista", b =>
                {
                    b.Property<int>("MotoristaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MotoristaID"));

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CategoriaCNH")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ViagemID")
                        .HasColumnType("int");

                    b.HasKey("MotoristaID");

                    b.HasIndex("ViagemID");

                    b.ToTable("Motoristas");
                });

            modelBuilder.Entity("LogisticERP.Domain.Veiculo", b =>
                {
                    b.Property<int>("VeiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VeiculoId"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<double>("CapacidadeCarga")
                        .HasColumnType("double");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Propriedade")
                        .HasColumnType("int");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<int?>("ViagemID")
                        .HasColumnType("int");

                    b.HasKey("VeiculoId");

                    b.HasIndex("ViagemID");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("LogisticERP.Domain.Viagem", b =>
                {
                    b.Property<int>("ViagemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ViagemID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataChegada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("HoraChegada")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraSaida")
                        .HasColumnType("time(6)");

                    b.Property<int>("MotoristaID")
                        .HasColumnType("int");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VeiculoID")
                        .HasColumnType("int");

                    b.HasKey("ViagemID");

                    b.ToTable("Viagens");
                });

            modelBuilder.Entity("LogisticERP.Domain.Motorista", b =>
                {
                    b.HasOne("LogisticERP.Domain.Viagem", null)
                        .WithMany("Motoristas")
                        .HasForeignKey("ViagemID");
                });

            modelBuilder.Entity("LogisticERP.Domain.Veiculo", b =>
                {
                    b.HasOne("LogisticERP.Domain.Viagem", null)
                        .WithMany("Veiculos")
                        .HasForeignKey("ViagemID");
                });

            modelBuilder.Entity("LogisticERP.Domain.Viagem", b =>
                {
                    b.Navigation("Motoristas");

                    b.Navigation("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
